id: armory_setup_account
learningObjectives: 
- Configure Armory account
hints:
- Any help here
startFlow:
  do:
  - actionId: armory_create_account
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Our deployment process is a nightmare and we have to do a better work there."
        delay: 1000
      - text: "We found a great tool called [Armory](https://www.armory.io/) that suppose to help us here. I've sent you an invite to ${user.email} - checkout your inbox and make sure you accept the invite"
        delay: 1500
      - text: ":instruction[Let me know when you're ready]"
        delay: 1500
trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Awesome! 
              delay: 2000
            - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: :instruction[If you need any help, just say **I'm stuck** to let me know].
                If that’s not the case - take your time and tell me once you're ready
                :)
              delay: 1000
